index:
    path: /
    controller: App\Controller\baseController::index

#lucky number (test)
#app_lucky_number:
#     path: /lucky/number
#    controller: App\Controller\LuckyController::number

login:
    path: /login
    controller: App\Controller\SecurityController::login

app_admin:
  path: /admin
  controller: App\Controller\AdminController::admin

modifcontact:
  path: /admin/contact/modifier
  controller: App\Controller\AdminController::contact

app_insertPhoto:
    path: /admin/photo/ajouter
    controller: App\Controller\AdminController::insertPhoto

app_deletePhoto:
    path: /admin/photo/supprimer/{id}
    controller: App\Controller\AdminController::deletePhoto

logout:
    path: /logout