#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#lucky number (test)
app_lucky_number:
      path: /lucky/number
      controller: App\Controller\LuckyController::number